# Generated by Django 5.0.4 on 2024-05-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
